# Generated by Django 4.2.3 on 2023-09-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookATable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=250)),
                ('date', models.DateTimeField()),
                ('num_people', models.IntegerField()),
                ('special_request', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
