# Generated by Django 4.2.4 on 2023-08-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_masterchef_socialchef'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterchef',
            name='social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.socialchef'),
        ),
    ]
