# Generated by Django 4.2.3 on 2023-09-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookatable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='special_request',
            field=models.TextField(max_length=300),
        ),
    ]
