# Generated by Django 4.2.3 on 2023-09-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bookatable_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
