# Generated by Django 4.2.5 on 2023-10-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bookatable_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('title',), 'verbose_name_plural': 'Menu'},
        ),
    ]
